---
title: "Network diagram from ORCID"
author: Adrian Barnett
date: "`r format(Sys.time(), '%d %B %Y')`"
fontsize: 12pt
output: word_document
params:
  orcid.ids1: NA
  orcid.ids2: NA
  orcid.ids3: NA
  orcid.ids4: NA
  orcid.ids5: NA
  orcid.ids6: NA
  orcid.ids7: NA
  orcid.ids8: NA
  orcid.ids9: NA
  orcid.ids10: NA
  curve: NA
  dtext: NA
  line.colour: NA
  box.colour: NA
  number.colour: NA
  text.colour: NA
  box.cex: NA
  box.height: NA
  box.size: NA
  box.type: NA
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warnings=FALSE, comment='', dpi = 400)
# next two lines for testing:
#library(rorcid)
#orcid.ids = c('0000-0003-3637-2423','0000-0001-6339-0374','0000-0002-5559-3267') # me, Nick, Anisa
```

```{r main.function, include=FALSE}
    orcid.ids  = c(params$orcid.ids1,params$orcid.ids2,params$orcid.ids3,params$orcid.ids4)
    orcid.ids = orcid.ids[orcid.ids!=''] # remove missing IDs
  n.names = length(orcid.ids)
  
  # check for repeated ORCID
  if(any(table(orcid.ids) > 1)){
    repeated = names(which(table(orcid.ids)>1))
    # remove repeats
    orcid.ids = unique(orcid.ids)
    n.names = length(orcid.ids)
  }
  
  # a) get names (loop)
  names = all.dois = NULL
  person.number = 0 # need a specific person count for when people drop out
  for (k in 1:n.names){
    bio = orcid_id(orcid = orcid.ids[k], profile='profile') # get basics
    first = bio[[1]]$`name`$`given-names`$value
    surname = bio[[1]]$`name`$`family-name`$value
    # add affiliation here?
    name = paste(gsub(' ', '', first), '\n', gsub(' ', '', surname), sep='')
 
  # b) get works and transform to DOss
    d = works(orcid_id(orcid = orcid.ids[k])) # get works as a tibble
    if(nrow(d)==0){
      # reduce number of names
      n.names = n.names - 1 
    }
    if(nrow(d)>0){
      person.number = person.number + 1
      names = c(names, name) # add to list of names
      dois = identifiers(d, type='doi') # get DOIs, not available for all papers
      dois = dois[duplicated(dois)==F]
      # to do, get EIDs where there's no DOI
      frame =  data.frame(k=person.number, name=name, dois=dois)
      all.dois = rbind(all.dois, frame)
    }
  }
  
  # matrix M of links
  M = matrix(nrow = n.names, ncol = n.names, byrow = TRUE, data = 0)

  # find common papers
  tab = with(all.dois, table(dois, k))
  tab[tab>1] = 1
  tab = tab[rowSums(tab)>1, ] # rows with a match
  if(nrow(tab)>0){ # only if there's some matches
    for (j in 1:nrow(tab)){
      pairs = as.numeric(names(which(tab[j,] == 1)))
      combs = combn(pairs, 2)
      for (k in 1:ncol(combs)){
        M[combs[1,k], combs[2,k]] = M[combs[1,k], combs[2,k]] + 1
      }
    }
  }
  
```


```{r plot, fig.width=6, fig.height=5}
    # plot
    par(mai=c(0.02,0.02,0.02,0.02))
    plotmat(M, name = names, 
            curve=params$curve, arr.width = 0, 
            box.col = params$box.colour, box.lcol = params$number.colour,
                 box.lwd = 2, cex = 1.1, 
            box.size = params$box.size, shadow.size=0, box.cex=params$box.cex,
                 box.type = params$box.type, txt.col = params$text.colour,
            dtext=params$dtext,
            box.prop = params$box.height, arr.lcol=params$line.colour, 
            arr.lwd=M)
```
